# Generated by Django 3.1.2 on 2022-01-19 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0002_customerdetail_ingredient_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='cheese',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='meat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='salad',
            field=models.IntegerField(default=0),
        ),
    ]
